.TH "C:/xampp/htdocs/usahawanekspress.com/intelmlm_template/Metro-UI-Mastered/docs/js Directory Reference" 3 "Mon Jan 6 2014" "Version 1" "intelMLM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/xampp/htdocs/usahawanekspress.com/intelmlm_template/Metro-UI-Mastered/docs/js Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBholder\fP"
.br
.ti -1c
.RI "directory \fBjquery\fP"
.br
.ti -1c
.RI "directory \fBmetro\fP"
.br
.ti -1c
.RI "directory \fBprettify\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBdocs\&.js\fP"
.br
.ti -1c
.RI "file \fBgithub\&.info\&.js\fP"
.br
.ti -1c
.RI "file \fBhitua\&.js\fP"
.br
.ti -1c
.RI "file \fBload-metro\&.js\fP"
.br
.ti -1c
.RI "file \fBmetro\&.min\&.js\fP"
.br
.ti -1c
.RI "file \fBstart-screen\&.js\fP"
.br
.in -1c
