.TH "C:/xampp/htdocs/usahawanekspress.com/intelmlm_include/debugger/Easy-Responsive-Tabs-to-Accordion-master/js Directory Reference" 3 "Mon Jan 6 2014" "Version 1" "intelMLM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/xampp/htdocs/usahawanekspress.com/intelmlm_include/debugger/Easy-Responsive-Tabs-to-Accordion-master/js Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBeasyResponsiveTabs\&.js\fP"
.br
.ti -1c
.RI "file \fBjquery-1\&.6\&.3\&.min\&.js\fP"
.br
.in -1c
