.TH "C:/xampp/htdocs/usahawanekspress.com/intelmlm_modules/Main/Zebra_Pagination-master/examples Directory Reference" 3 "Mon Jan 6 2014" "Version 1" "intelMLM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/xampp/htdocs/usahawanekspress.com/intelmlm_modules/Main/Zebra_Pagination-master/examples Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBexample1\&.php\fP"
.br
.ti -1c
.RI "file \fBexample2\&.php\fP"
.br
.in -1c
