.TH "C:/xampp/htdocs/usahawanekspress.com/intelmlm_template/Metro-UI-Mastered/js/jQuery-File-Upload-master/test Directory Reference" 3 "Mon Jan 6 2014" "Version 1" "intelMLM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/xampp/htdocs/usahawanekspress.com/intelmlm_template/Metro-UI-Mastered/js/jQuery-File-Upload-master/test Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBtest\&.js\fP"
.br
.in -1c
