.TH "C:/xampp/htdocs/usahawanekspress.com/intelmlm_template/Metro-UI-Mastered/js/jQuery-File-Upload-master/js Directory Reference" 3 "Mon Jan 6 2014" "Version 1" "intelMLM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/xampp/htdocs/usahawanekspress.com/intelmlm_template/Metro-UI-Mastered/js/jQuery-File-Upload-master/js Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBcors\fP"
.br
.ti -1c
.RI "directory \fBvendor\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBapp\&.js\fP"
.br
.ti -1c
.RI "file \fBjquery\&.fileupload-angular\&.js\fP"
.br
.ti -1c
.RI "file \fBjquery\&.fileupload-audio\&.js\fP"
.br
.ti -1c
.RI "file \fBjquery\&.fileupload-image\&.js\fP"
.br
.ti -1c
.RI "file \fBjquery\&.fileupload-jquery-ui\&.js\fP"
.br
.ti -1c
.RI "file \fBjquery\&.fileupload-process\&.js\fP"
.br
.ti -1c
.RI "file \fBjquery\&.fileupload-ui\&.js\fP"
.br
.ti -1c
.RI "file \fBjquery\&.fileupload-validate\&.js\fP"
.br
.ti -1c
.RI "file \fBjquery\&.fileupload-video\&.js\fP"
.br
.ti -1c
.RI "file \fBjquery\&.fileupload\&.js\fP"
.br
.ti -1c
.RI "file \fBjquery\&.iframe-transport\&.js\fP"
.br
.ti -1c
.RI "file \fBmain\&.js\fP"
.br
.in -1c
