.TH "C:/xampp/htdocs/usahawanekspress.com/intelmlm_template/Metro-UI-Mastered/js/Print-Specified-Area-Of-A-Page-PrintArea/demo Directory Reference" 3 "Mon Jan 6 2014" "Version 1" "intelMLM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/xampp/htdocs/usahawanekspress.com/intelmlm_template/Metro-UI-Mastered/js/Print-Specified-Area-Of-A-Page-PrintArea/demo Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBjquery-1\&.9\&.0\&.js\fP"
.br
.ti -1c
.RI "file \fBjquery\&.PrintArea\&.js\fP"
.br
.ti -1c
.RI "file \fBjquery\&.PrintArea\&.metro\&.js\fP"
.br
.in -1c
