.TH "C:/xampp/htdocs/usahawanekspress.com/intelmlm_template/Metro-UI-Mastered/js/jQuery-File-Upload-master Directory Reference" 3 "Mon Jan 6 2014" "Version 1" "intelMLM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/xampp/htdocs/usahawanekspress.com/intelmlm_template/Metro-UI-Mastered/js/jQuery-File-Upload-master Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBjs\fP"
.br
.ti -1c
.RI "directory \fBserver\fP"
.br
.ti -1c
.RI "directory \fBtest\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBGruntfile\&.js\fP"
.br
.in -1c
