.TH "C:/xampp/htdocs/usahawanekspress.com/intelmlm_modules/Main Directory Reference" 3 "Mon Jan 6 2014" "Version 1" "intelMLM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/xampp/htdocs/usahawanekspress.com/intelmlm_modules/Main Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBZebra_Pagination-master\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBadmin\&.php\fP"
.br
.ti -1c
.RI "file \fBcheckout_process\&.php\fP"
.br
.ti -1c
.RI "file \fBchoose_product\&.php\fP"
.br
.ti -1c
.RI "file \fBchoosepackage_colorbox\&.php\fP"
.br
.ti -1c
.RI "file \fBcolorbox_select_ebooks\&.php\fP"
.br
.ti -1c
.RI "file \fBebook_list_1\&.php\fP"
.br
.ti -1c
.RI "file \fBebook_payment\&.php\fP"
.br
.ti -1c
.RI "file \fBfeatures\&.php\fP"
.br
.ti -1c
.RI "file \fBgetbookinfo\&.php\fP"
.br
.ti -1c
.RI "file \fBguest\&.php\fP"
.br
.ti -1c
.RI "file \fBguest_main\&.php\fP"
.br
.ti -1c
.RI "file \fBguest_register\&.php\fP"
.br
.ti -1c
.RI "file \fBindex\&.php\fP"
.br
.ti -1c
.RI "file \fBkumpulan\&.php\fP"
.br
.ti -1c
.RI "file \fBMain\&.php\fP"
.br
.ti -1c
.RI "file \fBmake_payment\&.php\fP"
.br
.ti -1c
.RI "file \fBmake_payment2\&.js\fP"
.br
.ti -1c
.RI "file \fBmake_payment2\&.php\fP"
.br
.ti -1c
.RI "file \fBmember_main\&.php\fP"
.br
.ti -1c
.RI "file \fBmetro_guest_main\&.php\fP"
.br
.ti -1c
.RI "file \fBmy_account\&.php\fP"
.br
.ti -1c
.RI "file \fBorder_and_payment\&.php\fP"
.br
.ti -1c
.RI "file \fBpayment_process\&.php\fP"
.br
.ti -1c
.RI "file \fBpayment_receipt\&.php\fP"
.br
.ti -1c
.RI "file \fBpesanan\&.php\fP"
.br
.ti -1c
.RI "file \fBprocess_choose_package\&.php\fP"
.br
.ti -1c
.RI "file \fBpromosi\&.php\fP"
.br
.ti -1c
.RI "file \fBreceipt\&.php\fP"
.br
.ti -1c
.RI "file \fBstep_calculator\&.php\fP"
.br
.ti -1c
.RI "file \fBstep_kemudian\&.php\fP"
.br
.ti -1c
.RI "file \fBstep_seterusnya\&.php\fP"
.br
.ti -1c
.RI "file \fBtab_choose_and_payment\&.php\fP"
.br
.ti -1c
.RI "file \fBtab_choose_package\&.php\fP"
.br
.ti -1c
.RI "file \fBview_pesanan\&.php\fP"
.br
.in -1c
