.TH "CustomUploadHandler" 3 "Mon Jan 6 2014" "Version 1" "intelMLM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CustomUploadHandler \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUploadHandler\fP, and \fBUploadHandler\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBget\fP ($print_response=true)"
.br
.ti -1c
.RI "\fBdelete\fP ($print_response=true)"
.br
.ti -1c
.RI "\fBdelete\fP ($print_response=true)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBinitialize\fP ()"
.br
.ti -1c
.RI "\fBhandle_form_data\fP ($file, $index)"
.br
.ti -1c
.RI "\fBhandle_file_upload\fP ($uploaded_file, $name, $size, $type, $error, $index=null, $content_range=null)"
.br
.ti -1c
.RI "\fBset_additional_file_properties\fP ($file)"
.br
.ti -1c
.RI "\fBinitialize\fP ()"
.br
.ti -1c
.RI "\fBhandle_form_data\fP ($file, $index)"
.br
.ti -1c
.RI "\fBhandle_file_upload\fP ($uploaded_file, $name, $size, $type, $error, $index=null, $content_range=null)"
.br
.ti -1c
.RI "\fBset_additional_file_properties\fP ($file)"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for intelMLM from the source code\&.
