.TH "deprecated" 3 "Mon Jan 6 2014" "Version 1" "intelMLM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deprecated \- Deprecated List 

.IP "\fBGlobal \fBBaseFacebook::getApiSecret\fP ()\fP" 1c
Use getAppSecret instead\&. 
.PP
\fBSee Also:\fP
.RS 4
getAppSecret()  
.RE
.PP
.IP "\fBGlobal \fBBaseFacebook::setApiSecret\fP ($apiSecret)\fP" 1c
Use setAppSecret instead\&. 
.PP
\fBSee Also:\fP
.RS 4
setAppSecret()  
.RE
.PP
.IP "\fBGlobal \fBBaseFacebook::useFileUploadSupport\fP ()\fP" 1c
Use getFileUploadSupport instead\&. 
.PP
\fBSee Also:\fP
.RS 4
getFileUploadSupport() 
.RE
.PP
.PP

