.TH "FBPublic" 3 "Mon Jan 6 2014" "Version 1" "intelMLM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FBPublic \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBTransientFacebook\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBpublicParseSignedRequest\fP ($input)"
.br
.ti -1c
.RI "\fBpublicMakeSignedRequest\fP ($data)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBpublicBase64UrlDecode\fP ($input)"
.br
.ti -1c
.RI "static \fBpublicBase64UrlEncode\fP ($input)"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for intelMLM from the source code\&.
