.TH "FBPublicState" 3 "Mon Jan 6 2014" "Version 1" "intelMLM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FBPublicState \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBTransientFacebook\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBpublicGetState\fP ()"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const \fBSTATE\fP = 'foo'"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBgetPersistentData\fP ($key, $default=false)"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for intelMLM from the source code\&.
