.TH "FBPublicCookie" 3 "Mon Jan 6 2014" "Version 1" "intelMLM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FBPublicCookie \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBTransientFacebook\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBpublicGetSignedRequest\fP ()"
.br
.ti -1c
.RI "\fBpublicGetSignedRequestCookieName\fP ()"
.br
.ti -1c
.RI "\fBpublicGetMetadataCookie\fP ()"
.br
.ti -1c
.RI "\fBpublicGetMetadataCookieName\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for intelMLM from the source code\&.
