.TH "FBRecordMakeRequest" 3 "Mon Jan 6 2014" "Version 1" "intelMLM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FBRecordMakeRequest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBTransientFacebook\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBpublicGetRequests\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBmakeRequest\fP ($url, $params, $ch=null)"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for intelMLM from the source code\&.
