.TH "md__c_1_xampp_htdocs_usahawanekspress.com_intelmlm_include_debugger_zeroclipboard-1.2.3_docs_roadmap" 3 "Mon Jan 6 2014" "Version 1" "intelMLM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__c_1_xampp_htdocs_usahawanekspress.com_intelmlm_include_debugger_zeroclipboard-1.2.3_docs_roadmap \- Roadmap 
These are things that we have expressed interest in but haven't implemented yet\&. There is no order, if you feel like you can complete one of the tasks\&. Feel free to fork the project and send a pull request with the new code\&.
.PP
.SS "Rich Clipboard"
.PP
The Flash Clipboard API supports RichText (RTF), HTML, and custom data\&. We want to enable those as feasible\&. See Issues \fC#143\fP and \fC#152\fP\&.
.PP
.SS "HTML5 Clipboard API"
.PP
In a perfect world we wouldn't need \fBZeroClipboard\fP, and the browsers would just take care of it\&. We would like to write \fBZeroClipboard\fP to use the browser's clipboard API when available\&. See Issues \fC#171\fP and \fC#105\fP\&.
.PP
.SS "Flash tests"
.PP
We want to setup a unit test suite for the Flash file\&. See Issue \fC#43\fP\&. 
