.TH "md__c_1_xampp_htdocs_usahawanekspress.com_intelmlm_template__metro-_u_i-_mastered_js_j_query-_file-_upload-master__c_o_n_t_r_i_b_u_t_i_n_g" 3 "Mon Jan 6 2014" "Version 1" "intelMLM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__c_1_xampp_htdocs_usahawanekspress.com_intelmlm_template__metro-_u_i-_mastered_js_j_query-_file-_upload-master__c_o_n_t_r_i_b_u_t_i_n_g \- Issue Guidelines 
The issues tracker should only be used for \fBbugs\fP or \fBfeature requests\fP\&.
.PP
Please post \fBsupport requests\fP and \fBgeneral discussions\fP about this project to the \fCsupport forum\fP\&.
.PP
.SS "Bugs"
.PP
Please follow these guidelines before reporting a bug:
.PP
.IP "1." 4
\fBUpdate to the latest version\fP --- Check if you can reproduce the issue with the latest version from the \fCmaster\fP branch\&.
.IP "2." 4
\fBUse the GitHub issue search\fP --- check if the issue has already been reported\&. If it has been, please comment on the existing issue\&.
.IP "3." 4
\fBIsolate the demonstrable problem\fP --- Try to reproduce the problem with the \fCDemo\fP or with a reduced test case that includes the least amount of code necessary to reproduce the problem\&.
.IP "4." 4
\fBProvide a means to reproduce the problem\fP --- Please provide as much details as possible, e\&.g\&. server information, browser and operating system versions, steps to reproduce the problem\&. If possible, provide a link to your reduced test case, e\&.g\&. via \fCJSFiddle\fP\&.
.PP
.PP
.SS "Feature requests"
.PP
Please follow the bug guidelines above for feature requests, i\&.e\&. update to the latest version and search for exising issues before posting a new request\&.
.PP
Generally, feature requests might be accepted if the implementation would benefit a broader use case or the project could be considered incomplete without that feature\&.
.PP
If you need help integrating this project into another framework, please post your request to the \fCsupport forum\fP\&.
.PP
.SS "Pull requests"
.PP
\fCPull requests\fP are welcome and the preferred way of accepting code contributions\&.
.PP
However, if you add a server-side upload handler implementation for another framework, please continue to maintain this version in your own fork without sending a pull request\&. You are welcome to add a link and possibly documentation about your implementation to the \fCWiki\fP\&.
.PP
Please follow these guidelines before sending a pull request:
.PP
.IP "1." 4
Update your fork to the latest upstream version\&.
.IP "2." 4
Follow the coding conventions of the original repository\&. Changes to one of the JavaScript source files are required to pass the \fCJSLint\fP validation tool\&.
.IP "3." 4
Keep your commits as atomar as possible, i\&.e\&. create a new commit for every single bug fix or feature added\&.
.IP "4." 4
Always add meaningfull commit messages\&. 
.PP

