.TH "md__c_1_xampp_htdocs_usahawanekspress.com_intelmlm_template__metro-_u_i-_mastered__r_e_a_d_m_e" 3 "Mon Jan 6 2014" "Version 1" "intelMLM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__c_1_xampp_htdocs_usahawanekspress.com_intelmlm_template__metro-_u_i-_mastered__r_e_a_d_m_e \- Welcome 
Metro UI CSS a set of styles to create a site with an interface similar to Windows 8 Metro UI\&. This set of styles was developed as a self-contained solution\&.
.PP
.SS "Current Version"
.PP
.SS "2\&.0\&.12"
.PP
See details of definition on \fCmetroui\&.org\&.ua\fP
.PP
.SS "NuGet"
.PP
Now you can use \fCNuGet package\fP\&. To install Metro UI CSS 2\&.0, run the following command in the Package Manager Console: \fBPM> Install-Package Metro\&.UI\&.CSS\fP
.PP
.SS "Pull requests"
.PP
Please create pull requests to develop branch\&. Requests in master branch will be ignored\&.
.PP
.SS "Credits"
.PP
.IP "\(bu" 2
Metro UI CSS now is a Microsoft BizSpark Startup\&.
.IP "\(bu" 2
Normalize\&.css is a project by Nicolas Gallagher and Jonathan Neal\&.
.IP "\(bu" 2
Styles created using the \fCless\fP preprocessor
.PP
.PP
.SS "Browser Compatibility"
.PP
IE9+, Chrome, Firefox, Opera, Safari
.PP
.SH "License"
.PP
.PP
Metro UI CSS has MIT License
.PP
.SS "Old version"
.PP
Metro UI CSS 0\&.95 you can find in a branch \fCmetrouicss-0\&.95\fP 
