.TH "md__c_1_xampp_htdocs_usahawanekspress.com_intelmlm_template__metro-_u_i-_mastered__c_h_a_n_g_e_l_o_g" 3 "Mon Jan 6 2014" "Version 1" "intelMLM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__c_1_xampp_htdocs_usahawanekspress.com_intelmlm_template__metro-_u_i-_mastered__c_h_a_n_g_e_l_o_g \- Version 2\&.0\&.12 

.SS "Changes:"
.PP
.IP "\(bu" 2
upd datepicker for support calendar features
.PP
.PP
.SS "Version 2\&.0\&.11"
.PP
.SS "Changes:"
.PP
.IP "\(bu" 2
add start from monday for calendar
.IP "\(bu" 2
add show other days for calendar
.PP
.PP
.SS "Version 2\&.0\&.10"
.PP
.SS "Changes:"
.PP
.IP "\(bu" 2
add langs to calendar: en, fr, ua, ru
.PP
.PP
.SS "Version 2\&.0\&.9"
.PP
.SS "Changes:"
.PP
.IP "\(bu" 2
bugs fix
.IP "\(bu" 2
add locale support to calendar, datepicker and Date\&.format (to global set METRO_LOCALE = 'en' or 'ru', or use data-locale attribute)
.PP
.PP
.SS "Version 2\&.0\&.8"
.PP
.SS "Changes:"
.PP
.IP "\(bu" 2
bugs fix
.IP "\(bu" 2
add notices
.PP
.PP
.SS "Version 2\&.0\&.7"
.PP
.SS "Changes:"
.PP
.IP "\(bu" 2
fix color error in treeview
.IP "\(bu" 2
add minfied js in one file: metro\&.min\&.js
.PP
.PP
.SS "Version 2\&.0\&.6"
.PP
.SS "Changes:"
.PP
.IP "\(bu" 2
upd treeview, add events for collapse and expand node
.PP
.PP
.SS "Version 2\&.0\&.5"
.PP
.SS "Changes:"
.PP
.IP "\(bu" 2
init scroll bar component (prototype)
.IP "\(bu" 2
upd treeview
.IP "\(bu" 2
fix bugs
.PP
.PP
.SS "Version 2\&.0\&.4"
.PP
.SS "Changes:"
.PP
.IP "\(bu" 2
change dropdown menu default style
.IP "\(bu" 2
add dropdown menu inverse style
.IP "\(bu" 2
fix any bugs
.PP
.PP
.SS "Version 2\&.0\&.3"
.PP
.SS "Changes:"
.PP
.IP "\(bu" 2
fix any bugs
.PP
.PP
.SS "Version 2\&.0\&.2"
.PP
.SS "Changes:"
.PP
.IP "\(bu" 2
fixed minor bugs
.IP "\(bu" 2
new component streamer (prototype)
.PP
.PP
.SS "Version 2\&.0\&.1"
.PP
.SS "Changes:"
.PP
.IP "\(bu" 2
change buttons\&.less > button:active for remove dead zone tearly text in button
.IP "\(bu" 2
added new method value to slider
.PP
.PP
.SS "Limitation:"
.PP
.IP "\(bu" 2
no responsive module (only prototype)
.IP "\(bu" 2
no tiles drag feature 
.PP

