.TH "PersistentFBPublic" 3 "Mon Jan 6 2014" "Version 1" "intelMLM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PersistentFBPublic \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBFacebook\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBpublicParseSignedRequest\fP ($input)"
.br
.ti -1c
.RI "\fBpublicSetPersistentData\fP ($key, $value)"
.br
.ti -1c
.RI "\fBpublicGetPersistentData\fP ($key, $default=false)"
.br
.ti -1c
.RI "\fBpublicClearPersistentData\fP ($key)"
.br
.ti -1c
.RI "\fBpublicClearAllPersistentData\fP ()"
.br
.ti -1c
.RI "\fBpublicGetSharedSessionID\fP ()"
.br
.ti -1c
.RI "\fBpublicGetSharedSessionCookieName\fP ()"
.br
.ti -1c
.RI "\fBpublicGetHttpHost\fP ()"
.br
.ti -1c
.RI "\fBpublicGetHttpProtocol\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBpublicIsAllowedDomain\fP ($big, $small)"
.br
.ti -1c
.RI "static \fBpublicEndsWith\fP ($big, $small)"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for intelMLM from the source code\&.
