.TH "TransientFacebook" 3 "Mon Jan 6 2014" "Version 1" "intelMLM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TransientFacebook \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBBaseFacebook\fP\&.
.PP
Inherited by \fBFBAccessToken\fP, \fBFBGetCurrentURLFacebook\fP, \fBFBPublic\fP, \fBFBPublicCookie\fP, \fBFBPublicGetAccessTokenFromCode\fP, \fBFBPublicState\fP, \fBFBRecordMakeRequest\fP, and \fBFBRecordURL\fP\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBsetPersistentData\fP ($key, $value)"
.br
.ti -1c
.RI "\fBgetPersistentData\fP ($key, $default=false)"
.br
.ti -1c
.RI "\fBclearPersistentData\fP ($key)"
.br
.ti -1c
.RI "\fBclearAllPersistentData\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for intelMLM from the source code\&.
